version: '3'

services:
  cbioportal:
    image: cbioportal/cbioportal:demo-rfc72
    volumes:
      - $TEST_HOME/docker_compose/keycloak/samlKeystore.jks:/cbioportal-/samlKeystore.jks:ro
      - $E2E_WORKSPACE/keycloak/idp-metadata.xml:/cbioportal-webapp/client-tailored-saml-idp-metadata.xml:ro
    command: /bin/sh -c "rm -rf /cbioportal-webapp/lib/servlet-api-2.5.jar && java -Xms2g -Xmx4g -Ddat.method=none -Dmultithread.core_pool_size=1 -Dauthenticate=saml -Dspring.security.saml2.relyingparty.registration.cbio-idp.identityprovider.metadata-uri=classpath://saml2-idp-metadata.xml -Dsession.service.url=http://cbioportal-session:5000/api/sessions/my_portal/ -cp '/cbioportal-webapp:/cbioportal-webapp/lib/*' org.cbioportal.PortalApplication"
  keycloak:
    networks:
    - cbio-net
    container_name: keycloak
    image: jboss/keycloak:11.0.3
    restart: unless-stopped
    depends_on:
    - kcdb
    ports:
    - "8081:8080"
    environment:
    - DB_VENDOR=mysql
    - DB_ADDR=kcdb
    - DB_USER=keycloak
    - DB_PORT=3306
    - DB_PASSWORD=password
    - DB_DATABASE=keycloak
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - JDBC_PARAMS=${KEYCLOAK_JDBC_PARAMS:-useSSL=false&serverTimezone=UTC}

  kcdb:
    networks:
    - cbio-net
    image: ${DOCKER_IMAGE_MYSQL}
    container_name: kcdb
    restart: unless-stopped
    volumes:
    - $E2E_WORKSPACE/kc_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=keycloak
    command: --ssl=0 --lower_case_table_names=1
networks:
  cbio-net: 
